### PR TITLE
Bugfix: Tabs do not update with programmatic setting of Vue ref

### LINKED ISSUE #125: BUG: Tabs do not update with programmatic setting of Vue ref
The `Tabs` component styling doesn't update when a Vue ref is passed and changed programmatically, e.g.:
```vue
<template>
  <Tabs v-model="tab">
     <Tab href="tab_1">Tab 1</Tab>
     <Tab href="tab_2">Tab 2</Tab>
  </Tabs>

  <button @click="changeTabs">Change tabs</button>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

const tab = ref('tab_1')

const changeTabs = () => {
  tab.value = tab.value == 'tab_1' ? 'tab_2' : 'tab_1'
}
</script>
```

### PR DESCRIPTION
**Pull request by marichka-offen**
Closes #125 by updating the component to use a get/set computed property for the active tab

### CODE REVIEW

**Comment by znicholasbrown** [comment]
This is working great @marichka-offen - one request: when the tabs component is in overflow mode, focusing tabs would cause the tab to scroll into view. Can we match the behavior with programmatic model updates?

**Comment by pleek91** [comment]
> This is working great @marichka-offen - one request: when the tabs component is in overflow mode, focusing tabs would cause the tab to scroll into view. Can we match the behavior with programmatic model updates?

@znicholasbrown I looked at this with @marichka-offen and its not a simple fix. We're going to pull this of into a new issue and fix it separately so we can get these changes out.

**Comment by znicholasbrown** [comment]
Makes sense 👍🏻

**Review by pleek91 — APPROVED** [review]
LGTM, works as expected

**Pull request merged**
